export const studentInputs = [
	{
		id: "active",
		label: "Active",
		element: "checkbox",
	},
	{
		id: "assoc",
		label: "Assoc",
		element: "checkbox",
	},
	{
		id: "assoc_pastor",
		label: "Assoc Pastor",
		element: "checkbox",
	},
	{
		id: "church_membership",
		label: "Church Membership",
		element: "checkbox",
	},
	{
		id: "deceased",
		label: "Deceased",
		element: "checkbox",
	},
	{
		id: "first_name",
		label: "First Name",
		element: "input",
		type: "text",
		placeholder: "Your first name",
	},
	{
		id: "last_name",
		label: "Last Name",
		element: "input",
		type: "text",
		placeholder: "Your last name",
	},
	{
		id: "display_name",
		label: "Display Name",
		element: "input",
		type: "text",
		placeholder: "Your full name or nic",
	},
	{
		id: "adress",
		label: "Adress",
		element: "input",
		type: "text",
		placeholder: "Adress",
	},
	{
		id: "city",
		label: "City",
		component: "dropdown",
		list: ["LAX", "DEN"],
		placeholder: "Select City",
	},
	{
		id: "birth_day",
		label: "Birth Day",
		element: "input",
		type: "date",
	},
	{
		id: "cell_phone",
		label: "Phone",
		element: "input",
		type: "text",
		placeholder: "Phone Number",
	},
	{
		id: "church_id",
		label: "Church",
		component: "dropdown",
		list: ["IUMP", "GRACE"],
		placeholder: "Select Church",
	},
	{
		id: "collegue",
		label: "Collegue",
		element: "input",
		type: "number",
		placeholder: "Collegue Number",
	},
	{
		id: "grad_date",
		label: "Graduation Date",
		element: "input",
		type: "date",
	},
	{
		id: "cur_semest",
		label: "Semester",
		element: "input",
		type: "text",
		placeholder: "Semester",
	},
	{
		id: "email",
		label: "Email",
		element: "input",
		type: "email",
		placeholder: "Your Email",
	},
	{
		id: "emer_phone",
		label: "Emergency Phone",
		element: "input",
		type: "text",
		placeholder: "Your Phone",
	},
	{
		id: "etnhic_bck",
		label: "Etnhic Background",
		component: "dropdown",
		list: ["Spanic", "Asiatic"],
		placeholder: "Select your etnhic",
	},
	{
		id: "txthide",
		label: "",
		element: "input",
		type: "hidden",
		placeholder: "",
	},
];

export const courseInputs = [
	{
		id: "active",
		label: "Active",
		component: "Input",
		type: "text",
		placeholder: "Active",
	},
	{
		id: "adress",
		label: "Adress",
		component: "Input",
		type: "text",
		placeholder: "Adress",
	},
];
